server:
  port: ${SERVER-PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: demo
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA-SERVER:localhost}:${SERVER-PORT:8084}/eureka/
