server:
  port: 8080
spring:
  application:
    name: demo
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
demo-zuul:
  ribbon:
    listOfServers: demo-zuul:8080